# Fish by default
# set-option -g default-shell "/usr/bin/fish"

# Remove annoying escape key delay so vim isn't interfered.
set -s escape-time 0

# I use a mouse sometimes.
set -g mouse

# Easier keybind for prefix Ctrl+a
set -g prefix C-a

# Easy reload source config file
bind r source-file ~/.tmux.conf \; display "Reloaded config!"

# Change the split window keys
# Make it so the \ splits horizontal, - split vertical. New panes are in directory of split off
unbind %
unbind '"'
bind \\ split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"

# Change panes with Alt + vim motion
bind -n M-h select-pane -L
bind -n M-l select-pane -R
bind -n M-k select-pane -U
bind -n M-j select-pane -D

# Mouse toggle with m key
bind m set -g mouse \; display "Mouse: #{?mouse,ON,OFF}"

